### ISSUE TITLE
Swap out FingerprintManager for FingerprintManagerCompat.

### ISSUE THREAD

**Issue by skibz** [jariz/react-native-fingerprint-android#1]
when running the plugin on a phone without fingerprint hardware, this exception is thrown at bootstrap:

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/hardware/fingerprint/FingerprintManager;
at io.jari.fingerprint.FingerprintModule.<init>(FingerprintModule.java:33)
at io.jari.fingerprint.FingerprintPackage.createNativeModules(FingerprintPackage.java:22)
at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:954)
```

i researched further and managed to figure out that [this class](https://developer.android.com/reference/android/support/v4/hardware/fingerprint/FingerprintManagerCompat.html) needs to be used to determine if the phone is capable of reading fingerprints at runtime.

**Comment by jariz** [comment]
Nice find! This is definitely something that I should've done in the first place...
Will get on this as soon as I can.

**Comment by jariz** [comment]
Fixed in #4

**Comment by bnvinay92** [comment]
I would not do that. FingerprintManagerCompat doesn't correctly detect fingerprint hardware. https://code.google.com/p/android/issues/detail?id=231939 @jariz

**Comment by jariz** [comment]
@bnvinay92 uhhh, but having no support for pre-6.0 devices isn't a solution either  
This sucks, but I'd rather wait for google to fix FingerprintManagerCompat, then.

**Comment by bnvinay92** [comment]
Fingerprint hardware exists only on devices starting from Marshmallow. It didn't exist on pre-6.0 devices except on one device by Lava which has its own implementation of fingerprint detection which is not accessible to application developers anyway. @jariz

**Comment by jariz** [comment]
I know, but developers still want to have their apps target pre-6.0 devices, then use `isHardwareDetected` for example to check if it's available.   
If we'd rely on FingerprintManager solely, you wouldn't be able to compile your app for anything but 6.0+ devices, which isn't very realistic.   
It also seems the problem you mentioned only affects emulators? Why was this problem only now found?
