### ISSUE TITLE
Auth cancelation

### ISSUE THREAD

**Issue by spearmootz** [jariz/react-native-fingerprint-android#11]
the design guide shows the cancel button but there is no cancel fingerprint authentication api.

is there another way to achieve this?

**Comment by jariz** [comment]
No, but that's definitely something that should be added.

**Comment by spearmootz** [comment]
i see that in the actual code there is a `cancelAuthentication`, does this not work?

**Comment by jariz** [comment]
Probably, but not something that's added yet to this library.

**Comment by spearmootz** [comment]
lol, the functionality is in your library its just not documented. i just tried it.

there is a method .cancelAuthentication

and if called the authenticate catch method is called.

**Comment by jariz** [comment]
Oh, lmao.   
Sorry, I made it a while ago. If you could file a PR that documents it, it'd be much appreciated.

**Comment by spearmootz** [comment]
sir, this is done. thanks for merging the previous docs mr

**Comment by spearmootz** [comment]
@jariz hey, i wanted to show you what i created since it uses your library. its like a auth interface for android and ios and it provides a default ui for android

https://github.com/spearmootz/react-native-authenticate

**Comment by jariz** [comment]
@spearmootz 
Hey! That's really cool! I had the exact same idea but never got around to it, It's actually why I wrote this library initially!
Glad to see someone build it 😄
Thanks for the headsup, always love to see my work featured.

**Comment by spearmootz** [comment]
This library is pretty cool, the other iOS is ok but the same dude has a passcode for iOS but there is a bug and he hasn't merged the fix in like a year :(

But if the passcode becomes available it's a really quick plug-in

Thanks for the kudos

**Comment by jariz** [comment]
Shame. Maybe fork it and republish to another name on npm. (even if to only fix the issue for your lib)
