### ISSUE TITLE
Fingerprint Template 

### ISSUE THREAD

**Issue by bneiluj** [jariz/react-native-fingerprint-android#14]
Can you have access to the fingerprint template ? 

I would like to be able to fetch the fingerprint template in order to create the asymmetric keys.

**Comment by jariz** [comment]
Not possible with the library currently. Doubt it's possible at all.
As far as I know, you can pass a object to the SDK that gets encrypted with the fingerprint signature, but you never can straight up access the fingerprint 'template' itself.
This functionality is on [the todo list](https://github.com/jariz/react-native-fingerprint-android#todo), you're free to file a PR.

**Comment by bneiluj** [comment]
But the fingerprint has to be already stored in the keyStore by the user ? 
or 
Can you get the encrypted signature (even just the Public Key) from any user who puts his finger on the device ?

**Comment by jariz** [comment]
I don't think so, but feel free to proof me otherwise, I haven't studied the SDK that extensively.
