### ISSUE TITLE
Change minSdkVersion to 4

### ISSUE THREAD

**Issue by skibz** [jariz/react-native-fingerprint-android#2]
when deploying my application to phone i get this gradle build error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 23 declared in library [manager:react-native-fingerprint-android:unspecified] /Users/ant/github/pdr-manager/android/app/build/intermediates/exploded-aar/manager/react-native-fingerprint-android/unspecified/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="io.jari.fingerprint" to force usage
```

simple enough, so i went ahead and added `<uses-sdk tools:overrideLibrary="io.jari.fingerprint" />` to my application's `AndroidManifest.xml` which got the build working again. 

something tells me that what i did (above) shouldn't be necessary, however. perhaps the minimum sdk version for this library should be lower?

**Comment by skibz** [comment]
i've been trying to find out the lowest sdk version in which `FingerprintManagerCompat` is available.. is it available everywhere? 😖

**Comment by jariz** [comment]
Yes, 23 is way too high, oversight on my part.
FingerPrintManagerCompat is part of support library v4, which means the minimum required SDK should instead be 4. ([source](http://martiancraft.com/blog/2015/06/android-support-library/#v4))

**Comment by SarjuHansaliya** [comment]
But for [`FingerprintManager`](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html) , I think, We require API level 23.

**Comment by jariz** [comment]
Yes, for FingerpintManager. But not for FingerpintManagerCompat.  
Obviously this change can only be done after #1 is closed.

**Comment by SarjuHansaliya** [comment]
Agree @jariz 
So i think , min-sdk will be 4 but target will be 23.

**Comment by jariz** [comment]
Ah, yes. Target will stay the same.
