### ISSUE TITLE
Get the Asymmetric Keys

### ISSUE THREAD

**Issue by joshuachinemezu** [jariz/react-native-fingerprint-android#24]
Can you get the Asymmetric Keys from any user's fingerprint or even just the public key ?

Looks like you can only verify a fingerprint which was beforehand stored into Android Keystore by the user. Is that correct ?

Can I get the asymmetric keys and probably save it to the server?

**Comment by jariz** [comment]
No, currently the lib only confirms if a fingerprint classed as valid by the system was used.
AFAIK `CryptoObject` allows for encryption/decryption of data based on fingerprints.
It's on the todo list: https://github.com/jariz/react-native-fingerprint-android#todo

**Comment by joshuachinemezu** [comment]
Thanks for the quick response, I will like to contribute to this, buzz me [twitter.com/poeticdev](https://www.twitter.com/poeticdev)
