### ISSUE TITLE
Getting requested keys of a value that is not an object

### ISSUE THREAD

**Issue by purunep** [jariz/react-native-fingerprint-android#5]
I am trying to use  react-native-fingerprint-android. I have saved with npm.  However, 
When I import from 'react-native-fingerprint-android', I am getting 'requested keys of a value that is not an object '.
Did I miss anything?

**Comment by jariz** [comment]
Did you [install the package](https://github.com/jariz/react-native-fingerprint-android/blob/master/readme.md#installation)? Sounds like you didn't.

**Comment by purunep** [comment]
Thanks for your quick response. Yes, I did automatic install the package and its showing on node_module folder. However, I didn't link. I  just found that I need to link with react-native link command. It works now. Exploring again to use it..Thanks.
