### ISSUE TITLE
Android M Permissions

### ISSUE THREAD

**Issue by AndoKarim** [jariz/react-native-fingerprint-android#6]
Hello. 
I tried to use your lib on Android M but permissions don't have to be in Manifest. They have to be asked during the launching. Therefor, I used https://facebook.github.io/react-native/docs/permissionsandroid.html to ask for permissions. The problem is that there is not the fingerprint Permission. What do you think? 

Thanks.

**Comment by jariz** [comment]
It seems that the fingerprint permission is one of the permissions that you can't ask for (you can't ask for it natively either), so I'm afraid you have no other option but to add it to your manifest (at least, that's the conclusion I've drawn, but I can be incorrect).

**Comment by AndoKarim** [comment]
Ok thank you. I saw the list of the Permissions available and Fingerprint isn't on it so I think you're right. 
Do you have a tip to use Samsung SDK into the java files directly (until you include it on your lib).
Thanks!

**Comment by jariz** [comment]
Late response, but no, you'll have to fork this library and add support to it yourself. (I accept pull requests!)
